version: '3.8'

services:
    api: 
      image: rewatch-api
      build: 
        context: "."
      container_name: rewatch-api
      restart: always
      expose:
        - 80
        - 443
        - 3001
      ports:
        - 3001:3001
      volumes:
        - .:/var/www/html/rewatch/api